title: Paradoxdruid's ESO Trial Guides
description: Mid-tier builds, trial rosters, and other info.
show_downloads: false
google_analytics:
# theme: jekyll-theme-leap-day
theme: jekyll-theme-cayman

# nav_enabled: true
# heading_anchors: true
